// /api/chat.js
// QuantumRx chat proxy — system prompt hardcoded server-side
// Injects live weekly briefing context for "full briefing" + general questions
// Injects live Signals feed context per-vertical so AI/Energy/Space/Crypto/Policy
// always have current stories, even if that vertical didn't make the weekly top 10
// Session-limited to 8 messages per IP per 24h, KV-tracked
// Q-Sentinel threat enforcement runs before any logic
//
// v3 CHANGES — this is the core of the rework:
// Previously there were exactly two format triggers: a vertical keyword
// match (four-part single-story format) and the literal phrase "this
// week" (weekly-recap bullet format). Every other question, comparisons,
// hypotheticals, cross-story synthesis, either got force-fit into one of
// those two shapes, got BOTH instructions firing at once with no
// priority order, or got no instruction at all and the model improvised
// blind.
//
// classifyQuestion() now runs a real classification pass before anything
// else, in priority order (most specific pattern wins), and the response
// includes `responseFormat` directly in the JSON payload. The CLIENT no
// longer has to guess the shape of an answer from regex on the raw text,
// the server already knows, because it already decided.
//
// v2 CHANGES (retained): added HOT TAKE to the four-part format and to
// the pre-written SPECIFIC STORY CONTEXT direct-use fields, matching
// hot_take now generated by news-refresh.js's editorial card pass.

import { kv } from "@vercel/kv";
import { logRequest } from './request-logger.js';

const SESSION_LIMIT = 8;
const SESSION_TTL = 60 * 60 * 24; // 24h

const SIGNALS_VERTICALS = {
  aimoves: 'qrx_feed_aimoves',
  energy: 'qrx_feed_energy',
  space: 'qrx_feed_space',
  crypto: 'qrx_feed_crypto',
  policy: 'qrx_feed_policy',
  hot: 'qrx_feed_hot',
  robotics: 'qrx_feed_robotics',
  semis: 'qrx_feed_semis',
  quantum: 'qrx_feed_quantum',
};

const BASE_SYSTEM_PROMPT = `You are the QuantumRx Signal Analyst, the site assistant for quantumrx.eu. QuantumRx is an AI infrastructure publication and product business founded by W. T. Wallace, a satellite systems engineer and Manager of Fleet Strategy at SES.

Your job is to help visitors understand the week's signals, what QuantumRx covers, and which product or resource is right for them. Be direct, concise, and technically credible. No hype, no filler. If you do not know something, say so.

WHAT QUANTUMRX PUBLISHES

QuantumRx covers AI infrastructure, edge compute, connectivity, satellite systems, robotics, semiconductors, quantum computing, energy infrastructure, crypto infrastructure, and technology policy. Content is written for engineers, founders, and operators.

Signals at quantumrx.eu/signals -- a daily AI-curated news feed with eleven tabs: What's Hot, AI Moves, Crypto, Policy, Energy, Space, Robotics, Semis, Quantum, Social, and Search. Refreshed every day at 06:00 UTC.

This Week in Tech at quantumrx.eu/this-week-in-tech -- a weekly editorial briefing of ten stories selected from across all verticals, published every Monday.

THE FORGES

Pepe Legends at tools.quantumrx.eu -- use code PEPEFREE for a free card.
Lord of the Memes at forge.quantumrx.eu -- use code LOTMFREE for a free card.

PRODUCTS AND PRICING

All products are one-time purchases, instant download, no subscription, except hosted services which are monthly.

AI Kernel Stack -- 10 euros. MACK Framework -- 20 euros. Kit 01 Site Intelligence -- 49.99 euros DIY or 149 euros setup plus 59.99 euros monthly hosted. Kit 02 Deploy a Live AI Tool -- 49.99 euros. Kit 03 AI Trading Card Generator -- 49.99 euros. Built in a Week -- 8.99 euros, or 1.99 euros for subscribers. Everything Bundle -- 99 euros. Custom News Feed -- 149 euros setup plus 59.99 euros monthly. Custom Development -- from 1500 euros.

Subscribers get the book for 1.99 euros. Subscribe free at quantumrx.eu.

CORE CONSTRAINTS — always apply, regardless of question type

Never use em dashes. Keep every section tight, no filler sentences, no restating the question back. Do not invent specific numbers, names, dates, or facts that are not present in the data provided below, if the data does not actually support a confident answer, say so directly rather than guessing or hedging vaguely. Do not list multiple products unless explicitly asked to compare products, recommend one and ask a clarifying question if needed.`;

/**
 * Classifies the visitor's latest question into one of five response
 * shapes. Order matters — checked most-specific-first, so a question
 * like "who's winning the AI race this week" resolves to comparative,
 * not weekly_recap, even though it also contains "this week".
 *
 * Returns null if nothing matches, letting the caller fall back to
 * single_story (if a vertical keyword matched) or general (if not).
 */
function classifyQuestion(text) {
  const t = text.toLowerCase();

  if (/who'?s (winning|losing|ahead|behind|closest to|leading)|biggest threat to .+'?s? lead|threat to .+ lead/.test(t)) {
    return 'comparative';
  }

  if (/what happens if|what could (actually )?derail|biggest obstacle|biggest risk|could go wrong|bubble (actually )?pop/.test(t)) {
    return 'speculative';
  }

  if (/how (are|is) .+ connected|most talked.about|biggest local impact|headline (nobody|no one)|connect(s|ing)? .+ stor(y|ies)|what'?s not being talked about/.test(t)) {
    return 'synthesis';
  }

  if (/this week|the briefing|full briefing|strongest signal|crossing mainstream/.test(t)) {
    return 'weekly_recap';
  }

  return null;
}

/**
 * Tailored format instruction per question type. Only the ONE matching
 * block is added to a given request's prompt, not all five every time,
 * so the model gets a single unambiguous instruction instead of having
 * to pick between several.
 */
function getFormatInstruction(type) {
  const titleRule = `Start with: TITLE: one punchy line, a real headline, not a restatement of the question. This is on its own line, before everything else.\n\n`;

  switch (type) {
    case 'single_story':
      return titleRule + `RESPONSE FORMAT — SINGLE STORY

The visitor is asking about one specific story or signal. After the title, use this four-part structure with these exact labels:

WHAT IS IT: one sentence, plain language, no jargon.
WHY IT MATTERS: one to two sentences on the real consequence, specific, willing to say if something is overblown.
WHAT TO WATCH: one sharp, checkable sentence on the near-term signal to watch.
HOT TAKE: one sentence of genuine editorial opinion, whatever tone fits the story, skeptical, bullish, dismissive, excited. This is QuantumRx's own voice, not a summary. Never hedge it with "some say" or similar.`;

    case 'weekly_recap':
      return titleRule + `RESPONSE FORMAT — WEEKLY RECAP

The visitor is asking about the week overall, not one story. After the title, use the CURRENT WEEKLY BRIEFING section. List the top 3 stories as short bullet points, one line per story, covering what happened and why it matters in a single sentence each. Then, after the bullets, on its own line: TAKE: one sentence of genuine editorial opinion on the week as a whole, not a recap of what you just said, a real position on what it adds up to.`;

    case 'comparative':
      return titleRule + `RESPONSE FORMAT — COMPARATIVE

The visitor is asking a comparison or ranking question: who is ahead, behind, winning, losing, or closest on some specific competitive question. After the title, structure the answer as:

CANDIDATE: name — one sentence on their current position.
(repeat for 2 to 4 real, named candidates, drawn from the live data provided, not invented)
VERDICT: one sentence naming who is actually ahead right now and why, stated as a real position, not hedged.

If the data provided does not give you enough to name real candidates with confidence, say that plainly instead of inventing names.`;

    case 'speculative':
      return titleRule + `RESPONSE FORMAT — SPECULATIVE

The visitor is asking a hypothetical, obstacle, or risk question: what could go wrong, what's blocking something, what happens if. After the title, structure the answer as:

CLAIM: one sharp sentence answering the question directly, a real position, not a hedge.
REASONING: two to three sentences on why, grounded in the live data provided, not invented specifics.
WATCH: one concrete, checkable thing that would confirm or contradict this claim in the near term.`;

    case 'synthesis':
      return titleRule + `RESPONSE FORMAT — SYNTHESIS

The visitor is asking a question that requires connecting or comparing across multiple stories, not summarising one: what's connected, what's getting outsized attention, what international story had domestic effect. After the title, structure the answer as:

FINDING: one sentence naming the specific connection, paper, or story.
WHY IT MATTERS: two sentences.
DRAWN FROM: name the one or two specific stories or sources this is actually based on.

If nothing in the live data provided actually supports a real answer, say so rather than inventing a connection.`;

    default:
      return titleRule + `RESPONSE FORMAT — GENERAL

This is a general question, not about a specific story, the week overall, a comparison, a hypothetical, or cross-story synthesis. After the title, answer directly in plain prose, no special format required.`;
  }
}

function formatStoryList(items, label) {
  if (!items || !items.length) return `No current ${label} stories available.`;
  return items.slice(0, 8).map((s, i) =>
    `[${i}] TITLE: ${s.title}\nSUMMARY: ${s.summary || s.description || ''}\nSOURCE: ${s.source || ''}`
  ).join('\n\n');
}

/**
 * Every parser below returns the SAME shape:
 *   { title: string|null, sections: [{ label, text, style }] }
 *
 * style is one of 'normal' | 'dim' | 'verdict' | 'hottake', purely a
 * rendering hint for the client, same four visual treatments already
 * built for the single-story slide, just applied generically now.
 *
 * readLink is no longer parsed from the model's output at all — it's
 * derived server-side from the verticals actually fetched for context
 * (see the handler), which is deterministic and doesn't depend on the
 * model remembering to emit a marker.
 *
 * TITLE is asked for in every format instruction, but never trusted
 * alone: if it's missing, extractTitle() falls back to a truncated
 * version of the first section's text, so the card never has to show
 * with no headline at all.
 *
 * If a parser can't find the markers it expects (the model didn't
 * follow the format instruction), it falls back to one plain section
 * holding the full raw text, rather than returning something broken
 * or empty.
 */

function extractTitle(text) {
  const m = text.match(/TITLE:\s*(.+)/i);
  return m ? m[1].trim() : null;
}

function stripTitle(text) {
  return text.replace(/TITLE:\s*.+/i, '').trim();
}

function truncate(str, max) {
  if (!str) return '';
  const clean = str.trim();
  return clean.length > max ? clean.slice(0, max - 1).trim() + '…' : clean;
}

function fallbackSection(text) {
  return { title: truncate(text, 80), sections: [{ label: null, text: text.trim(), style: 'normal' }] };
}

/**
 * Wraps a parser's result to guarantee title is never null: use the
 * model's TITLE marker if present, otherwise derive one from the first
 * section's text. This runs on every parser's output, not just the
 * fallback path.
 */
function ensureTitle(result, rawText) {
  if (result.title) return result;
  const firstSectionText = result.sections[0] ? result.sections[0].text : rawText;
  return { ...result, title: truncate(firstSectionText, 80) };
}

function parseSingleStory(rawTextWithTitle) {
  const modelTitle = extractTitle(rawTextWithTitle);
  const text = stripTitle(rawTextWithTitle);

  const whatIs = text.match(/WHAT IS IT:\s*([\s\S]*?)(?=WHY IT MATTERS:|$)/i);
  const why = text.match(/WHY IT MATTERS:\s*([\s\S]*?)(?=WHAT TO WATCH:|$)/i);
  const watch = text.match(/WHAT TO WATCH:\s*([\s\S]*?)(?=HOT TAKE:|$)/i);
  const hot = text.match(/HOT TAKE:\s*([\s\S]*?)$/i);

  if (!whatIs) return ensureTitle({ title: modelTitle, ...fallbackSection(text) }, text);

  const sections = [];
  sections.push({ label: 'What is it', text: whatIs[1].trim(), style: 'normal' });
  if (why) sections.push({ label: 'Why it matters', text: why[1].trim(), style: 'normal' });
  if (watch) sections.push({ label: 'What to watch', text: watch[1].trim(), style: 'dim' });
  if (hot) sections.push({ label: 'QRx Take', text: hot[1].trim(), style: 'hottake' });

  return ensureTitle({ title: modelTitle, sections }, text);
}

function parseWeeklyRecap(rawTextWithTitle) {
  const modelTitle = extractTitle(rawTextWithTitle);
  const text = stripTitle(rawTextWithTitle);

  const takeMatch = text.match(/TAKE:\s*([\s\S]*?)$/i);
  const bulletText = takeMatch ? text.slice(0, takeMatch.index) : text;

  const lines = bulletText.split(/\n+/).map(l => l.trim()).filter(Boolean);
  const bulletLines = lines.filter(l => /^[-*•]\s+|^\d+[.)]\s+/.test(l));

  if (!bulletLines.length) return ensureTitle({ title: modelTitle, ...fallbackSection(text) }, text);

  const sections = bulletLines.map(l => ({
    label: null,
    text: l.replace(/^[-*•]\s+|^\d+[.)]\s+/, ''),
    style: 'normal',
  }));
  if (takeMatch) sections.push({ label: 'QRx Take', text: takeMatch[1].trim(), style: 'hottake' });

  return ensureTitle({ title: modelTitle, sections }, text);
}

function parseComparative(rawTextWithTitle) {
  const modelTitle = extractTitle(rawTextWithTitle);
  const text = stripTitle(rawTextWithTitle);

  const candidateMatches = [...text.matchAll(/CANDIDATE:\s*(.+)/gi)];
  const verdictMatch = text.match(/VERDICT:\s*([\s\S]*?)$/i);

  if (!candidateMatches.length) return ensureTitle({ title: modelTitle, ...fallbackSection(text) }, text);

  const sections = candidateMatches.map(m => ({
    label: 'Candidate',
    text: m[1].trim(),
    style: 'normal',
  }));
  if (verdictMatch) sections.push({ label: 'Verdict', text: verdictMatch[1].trim(), style: 'verdict' });

  return ensureTitle({ title: modelTitle, sections }, text);
}

function parseSpeculative(rawTextWithTitle) {
  const modelTitle = extractTitle(rawTextWithTitle);
  const text = stripTitle(rawTextWithTitle);

  const claim = text.match(/CLAIM:\s*([\s\S]*?)(?=REASONING:|$)/i);
  const reasoning = text.match(/REASONING:\s*([\s\S]*?)(?=WATCH:|$)/i);
  const watch = text.match(/WATCH:\s*([\s\S]*?)$/i);

  if (!claim) return ensureTitle({ title: modelTitle, ...fallbackSection(text) }, text);

  const sections = [{ label: 'Claim', text: claim[1].trim(), style: 'verdict' }];
  if (reasoning) sections.push({ label: 'Reasoning', text: reasoning[1].trim(), style: 'normal' });
  if (watch) sections.push({ label: 'Watch', text: watch[1].trim(), style: 'dim' });

  return ensureTitle({ title: modelTitle, sections }, text);
}

function parseSynthesis(rawTextWithTitle) {
  const modelTitle = extractTitle(rawTextWithTitle);
  const text = stripTitle(rawTextWithTitle);

  const finding = text.match(/FINDING:\s*([\s\S]*?)(?=WHY IT MATTERS:|$)/i);
  const why = text.match(/WHY IT MATTERS:\s*([\s\S]*?)(?=DRAWN FROM:|$)/i);
  const drawnFrom = text.match(/DRAWN FROM:\s*([\s\S]*?)$/i);

  if (!finding) return ensureTitle({ title: modelTitle, ...fallbackSection(text) }, text);

  const sections = [{ label: 'Finding', text: finding[1].trim(), style: 'verdict' }];
  if (why) sections.push({ label: 'Why it matters', text: why[1].trim(), style: 'normal' });
  if (drawnFrom) sections.push({ label: 'Drawn from', text: drawnFrom[1].trim(), style: 'dim' });

  return ensureTitle({ title: modelTitle, sections }, text);
}

function parseGeneral(rawTextWithTitle) {
  const modelTitle = extractTitle(rawTextWithTitle);
  const text = stripTitle(rawTextWithTitle);
  return ensureTitle({ title: modelTitle, ...fallbackSection(text) }, text);
}

/**
 * Single entry point — dispatches to the right parser for a given
 * classification, always returns the standard { title, sections }
 * shape no matter which type came in.
 */
function parseResponseByType(rawText, questionType) {
  switch (questionType) {
    case 'single_story': return parseSingleStory(rawText);
    case 'weekly_recap': return parseWeeklyRecap(rawText);
    case 'comparative': return parseComparative(rawText);
    case 'speculative': return parseSpeculative(rawText);
    case 'synthesis': return parseSynthesis(rawText);
    default: return parseGeneral(rawText);
  }
}

function buildSystemPrompt(briefing, signalsContext, pageContext, storyContext, questionType, chipGroundingStories) {
  let prompt = BASE_SYSTEM_PROMPT;

  if (briefing && briefing.stories && briefing.stories.length) {
    const storyList = briefing.stories.map((s, i) =>
      `[${i}] CATEGORY: ${s.category}\nTITLE: ${s.title}\nWHAT IS IT: ${s.what_is_it}\nWHY IT MATTERS: ${s.why_it_matters}\nWHAT NEXT: ${s.what_next}\nVELOCITY: ${s.velocity}\nMATURITY: ${s.media_maturity}\nOUTLETS: ${s.outlets || ''}`
    ).join('\n\n');
    prompt += `\n\nCURRENT WEEKLY BRIEFING (${briefing.weekLabel || 'this week'}, ${briefing.stories.length} stories, the editorial top picks of the week):\n\n${storyList}`;
  } else {
    prompt += `\n\nNo current weekly briefing is loaded.`;
  }

  if (signalsContext && Object.keys(signalsContext).length) {
    prompt += `\n\nLIVE SIGNALS FEED BY VERTICAL (refreshed daily, broader coverage than the weekly briefing top 10 -- use this for any vertical-specific question, since a vertical may have strong stories today even if it did not make this week's top 10):\n`;
    for (const [vertical, items] of Object.entries(signalsContext)) {
      prompt += `\n--- ${vertical.toUpperCase()} ---\n${formatStoryList(items, vertical)}\n`;
    }
  }

  if (pageContext) {
    prompt += `\n\n${pageContext}`;
  }

  // storyContext carries pre-written KV intelligence for a specific story the visitor tapped.
  // Inject it with highest priority — use this data directly rather than generating from scratch.
  if (storyContext) {
    prompt += `\n\nSPECIFIC STORY CONTEXT (visitor tapped this story — use the pre-written fields below directly to produce the four-part briefing, do not hallucinate or generate new content, format as WHAT IS IT / WHY IT MATTERS / WHAT TO WATCH / HOT TAKE using exactly what is provided. If HOT TAKE is not present in the data below, generate one sentence of genuine editorial opinion yourself rather than omitting the section):\n${storyContext}`;
  }

  // chipGroundingStories carries the EXACT stories this chip question was
  // generated from this morning — resolved server-side by getChipById() from
  // the chip's id, never from anything the client sends directly. This is
  // the authoritative and ONLY data source for the answer — the whole point
  // of grounding a chip at generation time is that the model shouldn't fall
  // back on frozen training knowledge for it.
  if (chipGroundingStories && chipGroundingStories.length) {
    const list = chipGroundingStories.map((s, i) =>
      `[${i}] TITLE: ${s.title}\nVERTICAL: ${s.vertical || ''}\nWHAT IS IT: ${s.what_is_it || ''}\nWHY IT MATTERS: ${s.why_it_matters || ''}\nWHAT NEXT: ${s.what_next || ''}\nHOT TAKE: ${s.hot_take || ''}\nSOURCE: ${s.source || ''}\nURL: ${s.url || ''}`
    ).join('\n\n');
    prompt += `\n\nCHIP GROUNDING DATA (this exact question was generated this morning from the specific stories below — use ONLY this data to answer, do not draw on general or training knowledge, do not invent facts not present here. If this data genuinely does not support a confident answer, say so as your short answer rather than reaching beyond it):\n\n${list}`;
  }

  // Exactly one format instruction, matching the classified question type.
  prompt += `\n\n${getFormatInstruction(questionType)}`;

  prompt += `\n\nIf SPECIFIC STORY CONTEXT is provided above, use it immediately for the response without asking clarifying questions, and treat this as a single_story response regardless of which format instruction appears above. If PAGE CONTEXT is provided, prioritise answering questions about that specific page or article first.`;

  return prompt;
}

async function getSessionCount(ip) {
  const key = `chatsession:${ip}`;
  try {
    const count = await kv.incr(key);
    if (count === 1) await kv.expire(key, SESSION_TTL);
    return count;
  } catch {
    return 0; // fail open if KV unavailable
  }
}

async function getWeeklyBriefing() {
  try {
    const stories = await kv.get('weekly_briefing_current');
    const meta = await kv.get('weekly_briefing_updated');
    if (!stories || !Array.isArray(stories) || !stories.length) return null;
    return {
      stories,
      weekLabel: meta?.weekLabel || null,
      updatedAt: meta?.updatedAt || null,
    };
  } catch {
    return null;
  }
}

// Detect which vertical(s) the user's latest message is asking about, so we
// only fetch the Signals KV keys actually needed rather than all nine every time
function detectVerticals(messages) {
  const lastUserMsg = [...messages].reverse().find(m => m.role === 'user');
  if (!lastUserMsg) return [];
  const text = lastUserMsg.content.toLowerCase();

  const matches = [];
  if (/\bai\b|artificial intelligence|model release|openai|anthropic|gemini/.test(text)) matches.push('aimoves');
  if (/energy|power|grid|nuclear|renewable|data.?center power/.test(text)) matches.push('energy');
  if (/space|satellite|orbit|rocket|launch|nasa|spacex|mars/.test(text)) matches.push('space');
  if (/crypto|blockchain|defi|token|bitcoin|ethereum/.test(text)) matches.push('crypto');
  if (/policy|regulation|legislation|government|export control/.test(text)) matches.push('policy');
  if (/robot|robotics|humanoid|automation/.test(text)) matches.push('robotics');
  if (/semiconductor|chip|semis|fab|foundry|tsmc|nvidia/.test(text)) matches.push('semis');
  if (/quantum/.test(text)) matches.push('quantum');
  if (/full briefing|strongest signal|crossing mainstream|what should i watch|this week/.test(text)) matches.push('hot');

  return [...new Set(matches)];
}

async function getSignalsContext(verticals) {
  if (!verticals.length) return {};
  const context = {};
  await Promise.all(verticals.map(async (v) => {
    const kvKey = SIGNALS_VERTICALS[v];
    if (!kvKey) return;
    try {
      const cached = await kv.get(kvKey);
      if (cached?.items && Array.isArray(cached.items)) {
        context[v] = cached.items;
      }
    } catch {
      // skip silently, this vertical just won't be in context
    }
  }));
  return context;
}

// Resolves a chip's REAL grounding server-side from its id, rather than
// trusting whatever grounding blob a client might claim. A chip id has the
// shape "YYYY-MM-DD_N" (see generate-chat-chips.js) — N is that chip's
// index in the day's stored, filtered chips array. If the id doesn't match
// that shape (e.g. a bootstrap id, or a client sending garbage), or the
// dated record no longer exists, or the index is out of range, this
// returns null and the caller falls back to normal free-text classification.
// This is the only path chipGroundingStories/questionType can come from —
// the client never gets to assert its own grounding text or response format.
async function getChipById(chipId) {
  if (typeof chipId !== 'string') return null;
  const match = chipId.match(/^(\d{4}-\d{2}-\d{2})_(\d+)$/);
  if (!match) return null;
  const [, date, idxStr] = match;
  const idx = Number(idxStr);
  try {
    const record = await kv.get(`daily_chat_chips:${date}`);
    const chip = record?.chips?.[idx];
    if (!chip || chip.id !== chipId || !chip.responseFormat || !Array.isArray(chip.groundedStories) || !chip.groundedStories.length) {
      return null;
    }
    return { responseFormat: chip.responseFormat, groundedStories: chip.groundedStories };
  } catch {
    return null;
  }
}

async function getSentinelAction(ip) {
  const kvUrl = process.env.UPSTASH_REDIS_REST_URL;
  const kvToken = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!kvUrl || !kvToken) return null;
  try {
    const res = await fetch(
      // Raw ip — must match how writeAutoBlock() in request-logger.js writes
      // the key. encodeURIComponent here would break the match for IPv6 IPs.
      `${kvUrl}/get/threat_action:${ip}`,
      { headers: { Authorization: `Bearer ${kvToken}` }, signal: AbortSignal.timeout(800) }
    );
    if (!res.ok) return null;
    const data = await res.json();
    if (!data.result) return null;
    let parsed;
    try {
      parsed = JSON.parse(data.result);
    } catch {
      return null;
    }
    if (parsed.action) return parsed.action;
    if (parsed.value) {
      try {
        const inner = JSON.parse(parsed.value);
        return inner.action || null;
      } catch {
        return null;
      }
    }
    return null;
  } catch { return null; }
}

function escapeHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

function warningPage(ip) {
  const safeIp = escapeHtml(ip);
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Access Monitored</title><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a0c;color:#e0e0e0;font-family:-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:40px 20px}.inner{max-width:520px;text-align:center}.badge{margin-bottom:28px}.card{border:1px solid rgba(255,95,109,.25);background:rgba(255,95,109,.04);border-radius:14px;padding:44px 40px}h1{color:#ff5f6d;font-size:12px;letter-spacing:.22em;text-transform:uppercase;margin-bottom:20px}p{font-size:14px;line-height:1.75;color:rgba(255,255,255,.55);margin-bottom:14px}.ref{margin-top:18px;padding-top:16px;border-top:1px solid rgba(255,255,255,.07);font-size:11px;color:rgba(255,255,255,.22);font-family:monospace}.footer{margin-top:20px;font-size:10px;color:rgba(255,255,255,.16)}</style></head><body><div class="inner"><div class="badge"><svg width="48" height="48" viewBox="0 0 24 24" fill="none"><path d="M12 2L4 6v6c0 5.5 3.8 10.7 8 12 4.2-1.3 8-6.5 8-12V6L12 2z" fill="#1e3a8a" stroke="#38bdf8" stroke-width="1"/><path d="M9 12l2 2 4-4" stroke="#fff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="card"><h1>Access Monitored</h1><p>Unusual activity has been detected from your connection.</p><p>This endpoint is monitored and protected. All request metadata is logged.</p><p>If you believe this is an error, normal access will resume automatically.</p><div class="ref">ref: ${safeIp} &middot; ${new Date().toISOString()}</div></div><div class="footer">QuantumRx &middot; monitored by Q-Sentinel</div></div></body></html>`;
}

const LIMIT_REACHED_TEXT = `You've reached the free limit of 8 questions for this session.

For unlimited access to the Signal Analyst, full weekly briefings, and daily Signals coverage, subscribe free at quantumrx.eu. Your session resets in 24 hours either way.`;

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', 'https://www.quantumrx.eu');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const ip = await logRequest(req, {
    checkBody: true,
    expectedFields: ['messages'],
  });

  const sentinelAction = await getSentinelAction(ip);
  if (sentinelAction === 'block') {
    return res.status(403).setHeader('Content-Type', 'text/html').end(warningPage(ip));
  }
  if (sentinelAction === 'honeypot') {
    return res.status(200).json({ content: [{ type: 'text', text: 'I can help you with that. What would you like to know?' }] });
  }

  // Session limit check
  const sessionCount = await getSessionCount(ip);
  if (sessionCount > SESSION_LIMIT) {
    return res.status(200).json({ content: [{ type: 'text', text: LIMIT_REACHED_TEXT }], limitReached: true });
  }

  const { messages, pageContext, storyContext, chipId } = req.body;
  if (!messages || !Array.isArray(messages)) {
    return res.status(400).json({ error: 'Invalid request' });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY_Chat;

    const lastUserMsg = [...messages].reverse().find(m => m.role === 'user');
    const lastUserText = lastUserMsg ? lastUserMsg.content : '';

    let verticals = [];
    let questionType;
    let chipGroundingStories = null;

    // A pre-grounded chip (generated fresh this morning by
    // generate-chat-chips.js) already carries its exact source stories and
    // its correct response format, decided once, by the same model that
    // phrased the question, with full context. The client only ever sends
    // the chip's id — getChipById() resolves the real grounding server-side
    // from KV, so nothing the client claims about grounding is trusted.
    const resolvedChip = chipId ? await getChipById(chipId) : null;
    if (resolvedChip) {
      questionType = resolvedChip.responseFormat;
      chipGroundingStories = resolvedChip.groundedStories;
    } else {
      verticals = detectVerticals(messages);
      const patternType = classifyQuestion(lastUserText);

      // Cross-cutting question types (comparative/speculative/synthesis) still
      // need SOME live data to reason over. If no vertical keyword matched,
      // default to the broadest feed rather than leaving them with nothing
      // but the weekly briefing — this closes the gap where a question like
      // "who's closest to cracking fusion" got zero live context at all.
      if (!verticals.length && ['comparative', 'speculative', 'synthesis'].includes(patternType)) {
        verticals = ['hot'];
      }

      // storyContext (a tapped story) always forces single_story regardless
      // of question wording, matching the note appended in buildSystemPrompt.
      questionType = storyContext
        ? 'single_story'
        : (patternType || (verticals.length ? 'single_story' : 'general'));
    }

    const [briefing, signalsContext] = await Promise.all([
      getWeeklyBriefing(),
      // No need to hit the live Signals KV feed at all for a pre-grounded
      // chip — the exact stories it needs are already attached.
      chipGroundingStories ? Promise.resolve({}) : getSignalsContext(verticals),
    ]);

    const systemPrompt = buildSystemPrompt(briefing, signalsContext, pageContext || null, storyContext || null, questionType, chipGroundingStories);

    const contents = messages.map(m => ({
      role: m.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: m.content }]
    }));

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: systemPrompt }] },
          contents,
          generationConfig: { maxOutputTokens: 2048, temperature: 0.7 }
        })
      }
    );
    const data = await response.json();
    if (!response.ok) {
      console.error('Gemini error:', data);
      return res.status(500).json({ error: 'Gemini API error' });
    }
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || 'No response generated.';
    const parsed = parseResponseByType(text, questionType);

    // readLink is derived here, not parsed from the model's output. For a
    // pre-grounded chip, use the vertical it was actually generated from;
    // otherwise, whichever vertical was fetched for a free-typed question.
    const readLink = chipGroundingStories
      ? (chipGroundingStories[0]?.vertical || null)
      : (verticals.length ? verticals[0] : null);

    return res.status(200).json({
      content: [{ type: 'text', text }], // raw text retained for backward compatibility / debugging
      responseFormat: questionType,
      title: parsed.title,
      sections: parsed.sections,
      readLink,
      sessionCount,
      sessionLimit: SESSION_LIMIT,
      weekLabel: briefing?.weekLabel || null,
      storyCount: briefing?.stories?.length || 0,
    });
  } catch (err) {
    console.error('Proxy error:', err);
    return res.status(500).json({ error: 'Internal server error' });
  }
}
